### PR TITLE
new metric, developer per dollar

### PR DESCRIPTION
**Pull request by ncc220**
If I were deciding whether my business should invest in open source software would be comparing the cost of investing to the cost of hiring devs to make software in house, so I made a metric to do that

### CODE REVIEW

**Comment by mbbroberg** [comment]
Thanks for sending this over @ncc220 -- I'll dig more into this and bring it up in our next community meeting (next Thursday). 

In the meantime, please sign the commits following DCO bot's advice 🤖

**Comment by LawrenceHecht** [comment]
Developer per dollar doesn't scale across regions with vastly different wages. 

The topic is worthy of further discussion. One option is to frame the value in terms of % of a company's budget for IT and software development.

**Comment by mbbroberg** [comment]
Hey @ncc220, thanks again for sharing this idea for a metric. There is without a doubt something we need to capture in Value WG that answers the offered question: 

> Question: Would it be cheaper for a company to build software in house, or invest in open source software instead?

@vinodkahuja pinging you as it can relate to where you go with the financial-side of this project's focus areas.

**Comment by mbbroberg** [comment]
Thanks again for this metric proposal. Before we can add it in, we're taking the time to make sure we're answering the right questions with the right metrics. You can see more on how in #88 and join us on June 4th to continue that effort.

**Comment by mbbroberg** [comment]
Hey @ncc220 -- we've hit a major milestone with #88 and we now have meaningful Focus Areas for all metrics. The next steps for us to review your proposed metric as a community. To make this more inclusive to, review I've moved it to a Google doc for now and I've added it to a future [Value WG agenda](https://docs.google.com/document/d/1qWAV4ExtwcY3mSzIb9sYOUENt4Pi1BD7APjnRTCnZZs/edit#). 

See #105 and join in a future meeting if time permits.

**Pull request closed without merging**
