### PR TITLE
Popularity Metric for Living Wage

### PR DESCRIPTION
**Pull request by hickmanjv**
I am a student of Sean Goggins. We needed to finished a metric and create a pull request back to the base repo.

Joshua Hickman

### CODE REVIEW

**Comment by mbbroberg** [comment]
Hey @hickmanjv, thanks for submitting this to the project. Here are a few thoughts:

- First, please follow [these instructions](https://github.com/chaoss/wg-value/pull/83/checks?check_run_id=628351623) to sign the DCO
- The popularity element of this metric is implied in the definition. I think it's fair to focus on it being a singular (synthetic metric)
- I believe you're offering a metric from the perspective of an individual looking to maximize their hiring potential. Though I also see funding potential, which is from the perspective of a corporation of venture capital firm. It'd be helpful to center on a single persona, or clarify when different personas can use the same metric.
- Does this metric overlap with any others in the project? 

There is an opportunity to either edit this toward that ends, or to consider this a part of another working group's questions. To be fair, it's hard to see that beyond the README since our focus areas are a work in progress. 

I hope the feedback is helpful - let me know if you have questions and let me know how you'd like to proceed.

**Comment by hickmanjv** [comment]
Thanks for looking it over Matt,

I’ve followed those instructions and keep getting rebase errors and I am very new to this process. I cannot get them to clear as to sign them off.


“””
First, rewinding head to replay your work on top of it...
Applying: Update organizational-project-skill-demand.md
Applying: Update Labor Investment (Heading Issue)
Applying: Update social-currency-metric-system.md
Applying: remove trailing whitespace
Applying: Update labor_investment.md
Applying: minor typo fix
Applying: Update social-currency-metric-system.md
Applying: Update organizational-project-skill-demand.md
Applying: move images
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
error: Your local changes to the following files would be overwritten by merge:
focus-areas/ecosystem/scms-0-circle2.png
focus-areas/ecosystem/scms-1-dashboard.png
focus-areas/ecosystem/scms-2-tool-example.png
focus-areas/ecosystem/scms-3-expanded-comment.png
Please commit your changes or stash them before you merge.
Aborting
error: Failed to merge in the changes.
Patch failed at 0009 move images
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort”.
“””




That is the error I get from the rebase.

I don’t know how to fix it from here. When I use ‘git am —show-current-patch’ I get:




“””
commit 1a4e808427deb2da6a7a61746b638dccff094f71
Author: Georg J.P. Link <linkgeorg@gmail.com<mailto:linkgeorg@gmail.com>>
Date:   Sun Jan 26 16:35:15 2020 +0100

    move images



    Signed-off-by: Georg J.P. Link <linkgeorg@gmail.com<mailto:linkgeorg@gmail.com>>

diff --git a/focus-areas/ecosystem/scms-0-circle2.png b/focus-areas/ecosystem/images/scms-0-circle2.png
similarity index 100%
rename from focus-areas/ecosystem/scms-0-circle2.png
rename to focus-areas/ecosystem/images/scms-0-circle2.png
diff --git a/focus-areas/ecosystem/scms-1-dashboard.png b/focus-areas/ecosystem/images/scms-1-dashboard.png
similarity index 100%
rename from focus-areas/ecosystem/scms-1-dashboard.png
rename to focus-areas/ecosystem/images/scms-1-dashboard.png
diff --git a/focus-areas/ecosystem/scms-2-tool-example.png b/focus-areas/ecosystem/images/scms-2-tool-example.png
similarity index 100%
rename from focus-areas/ecosystem/scms-2-tool-example.png
rename to focus-areas/ecosystem/images/scms-2-tool-example.png
diff --git a/focus-areas/ecosystem/scms-3-expanded-comment.png b/focus-areas/ecosystem/images/scms-3-expanded-comment.png
similarity index 100%
rename from focus-areas/ecosystem/scms-3-expanded-comment.png
rename to focus-areas/ecosystem/images/scms-3-expanded-comment.png

“”"


Any help I can get to resolve this would be appreciated.


Yes, from attending the wg-value meeting today this metric would most definitely be a synthetic metric. As I was creating it and thinking through it, I did see how it could be used for individual developers and business investment. I was unsure how to present that inside the metric as this was my first attempt and was following the template like a lifeline.

I was getting a sense that this metric did overlap some others such as job opportunity, however, I didn’t see any of the data analytics in this fashion. I was coming at this metric from a business perspective. Companies have had centuries to flesh out their data analytic schemes and use those for better forecasting. I wanted to try and apply that thinking to a metric that would allow us to forecast the projects with the most potential.


Thank you very much for the feedback.

Josh

On May 7, 2020, at 11:39 AM, Matt Broberg <notifications@github.com<mailto:notifications@github.com>> wrote:



Hey @hickmanjv<https://github.com/hickmanjv>, thanks for submitting this to the project. Here are a few thoughts:

  *   First, please follow these instructions<https://github.com/chaoss/wg-value/pull/83/checks?check_run_id=628351623> to sign the DCO
  *   The popularity element of this metric is implied in the definition. I think it's fair to focus on it being a singular (synthetic metric)
  *   I believe you're offering a metric from the perspective of an individual looking to maximize their hiring potential. Though I also see funding potential, which is from the perspective of a corporation of venture capital firm. It'd be helpful to center on a single persona, or clarify when different personas can use the same metric.
  *   Does this metric overlap with any others in the project?

There is an opportunity to either edit this toward that ends, or to consider this a part of another working group's questions. To be fair, it's hard to see that beyond the README since our focus areas are a work in progress.

I hope the feedback is helpful - let me know if you have questions and let me know how you'd like to proceed.

**Comment by sgoggins** [comment]
can we delete the .DS_store files?

**Comment by mbbroberg** [comment]
Hey! I know you were on the meeting, but I'll add this here as well: 

Thanks again for this metric proposal. Before we can add it in, we're taking the time to make sure we're answering the right questions with the right metrics. You can see more on how in #88 and join us on June 4th to continue that effort.

**Comment by GeorgLink** [comment]
we'll continue to develop this metric in #104 

Closing this PR. When we are done developing the metric, we'll create a new PR.

**Pull request closed without merging**
