### PR TITLE
Create organizational-influence.md

### PR DESCRIPTION
**Pull request by vinodkahuja**
Organizational Influence release candidate metric.

Signed-off-by: Vinod K. Ahuja  <vahuja@unomaha.edu>

### CODE REVIEW

**Comment by GeorgLink** [comment]
Please fix DCO

Ideally, combine this PR with #148

**Comment by vinodkahuja** [comment]
@GeorgLink I have already provided "Signed-off-by: Vinod K. Ahuja vahuja@unomaha.edu" in my pull request but still, DCO fails it. It always does with my pull request. I am not sure what is the underlying cause.  
Further, I created these PRs through Github web UI and it did not provide me the option to merge two patches in one PR.

**Comment by GeorgLink** [comment]
Combining changes in GitHub UI for only one PR: After creating the first PR, you can continue to edit the branch that was created and it will update that PR -- no need to create a new branch or a new PR.

DCO fails are curious. My guess is that your name or email address doesn't match your GitHub provile information that the bot compares with. I've had the issue of a minor name spelling leading to failed checks. -- I'll set your DCO check to "pass" since you have it included in the commit.

**Comment by vinodkahuja** [comment]
@GeorgLink done. Please accept this PR and reject PR 148

**Comment by GeorgLink** [comment]
Done

**Pull request merged**
