### PR TITLE
Create academic-open-source-project-impact.md

### PR DESCRIPTION
**Pull request by vinodkahuja**
Release candidate metric academic-open-source-project-impact

Signed-off-by: Vinod K. Ahuja <vahuja@unomaha.edu>

### CODE REVIEW

**Comment by GeorgLink** [comment]
The Academic Value folder needs a README following the template: https://github.com/chaoss/governance/blob/master/templates/focus-areas.md#template-for-wgfocus-areasfocus-area-namereadmemd

**Comment by vinodkahuja** [comment]
@GeorgLink Done. Created folder readme.

**Review by GeorgLink — APPROVED** [review]
Thanks @vinodkahuja !

LGTM

**Comment by GeorgLink** [comment]
Ping @klumb -- Please merge when ready to add to website (I assume after website migration)

**Pull request merged**
