### PR TITLE
Project Popularity Metric

### PR DESCRIPTION
**Pull request by vinodkahuja**
Signed-off-by: Vinod K. Ahuja  <vahuja@unomaha.edu>

### CODE REVIEW

**Comment by GeorgLink** [comment]
May I suggest to prepend the images with the metric name: `images/<metric-name>_<image-name>`

**Comment by vinodkahuja** [comment]
@klumb  I have revised the name as proposed. 

@GeorgLink  github is not providing me the option to edit the name of binary file like png.

**Comment by GeorgLink** [comment]
If GitHub is being stubborn, maybe clone repo locally and then push changes
back to GitHub?

**Comment by vinodkahuja** [comment]
@GeorgLink Renamed both image.

**Comment by klumb** [comment]
@GeorgLink how does this look?

**Review by GeorgLink — APPROVED** [review]
LGTM Thanks @vinodkahuja

**Pull request merged**
