### PR TITLE
improvements in CoC and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vchrombie**
1. Updated the CoC according to the latest one. https://github.com/chaoss/governance/pull/103
2. Add information about the DCO and fixed the formatting issue.

### CODE REVIEW

**Comment by vchrombie** [comment]
> The "signed-off-by" needs to be only on the commit, not the pull request message. :)

Ok. Actually, I didn't actually type it. It was automatically generated so, I didn't touch it. Anyways I will clear that before sending a PR.

**Comment by GeorgLink** [comment]
> Ok. Actually, I didn't actually type it. It was automatically generated so

Yes, I know. GitHub pulls the commit message into the pull request message. Yes, I suggest removing it.

**Comment by vchrombie** [comment]
> > Ok. Actually, I didn't actually type it. It was automatically generated so
> 
> Yes, I know. GitHub pulls the commit message into the pull request message. Yes, I suggest removing it.

Sure. :+1:

**Comment by andyl** [comment]
Good catch - thank you Venu!

**Pull request merged**
