### PR TITLE
Strandardize repository structure of working group

### PR DESCRIPTION
**Pull request by friyaz**
Refer to issue #129.
 
This [google doc](https://docs.google.com/document/d/1chPzgJa49sO_f3wVqp_NLJupSVyKHSVyuFuwzl4m4KI/edit#) describes the proposed structure.

### CODE REVIEW

**Comment by friyaz** [comment]
I am not sure what to add in .gitignore.

**Comment by vchrombie** [comment]
Hi @friyaz, thanks for opening a PR and for the awesome work. I have some comments about the PR. It would be great If you can take some time and work on them so that the repo is cleaned in one PR. Let me know if you have any issue and you need any help.

#### broken links
There are a few broken links, some because of the changes in the PR. It would be great If you can fix them.
1. In [Contributing](https://github.com/chaoss/wg-value#contributing) section, `Core Contributor` link is broken. You can make the changes under [Contributors](https://github.com/chaoss/wg-value#contributors).
```
- **Maintainers**
+ #### Maintainers

- **Core Contributors**
+ #### Core Contributors
```
2. In the [Join the Working Group](https://github.com/chaoss/wg-value#join-the-working-group) section, link in the second point is broken `(information below)`. Need to point to the correct anchor.
3. Broken link in [License](https://github.com/chaoss/wg-value#license) section because of the new change in the file.

#### .gitignore
> I am not sure what to add in .gitignore.

There are some awesome resources for this, [octocat .gitignore gist](https://gist.github.com/octocat/9257657) and [github/gitignore](https://github.com/github/gitignore). But, I feel as these working groups won't be having much code, you can go with the basic ones. Feel free to add some more to the list.

```
# OS generated files #
######################
.DS_Store
.DS_Store?
._*
```

#### focus-areas
As per the doc guidelines, metric files should be in the format `/focus-areas/<focus-area-name>/<metric-name>.md`. Few files don't follow this format in `communal-value` and `organizational-value` folders.
For example, `/focus-areas/communal-value/project_velocity.md` should be changed to `/focus-areas/communal-value/project-velocity.md`. Please mind the potential broken links in the readme.

Also, the images should be of the format `/focus-areas/<focus-area-name>/images/<metric-name>_<image-name>.png` but most of the folders don't follow this.
For example, `/focus-areas/individual-value/images/_google_trends.png` should be changed `/focus-areas/individual-value/images/organizational-project-skill-demand_google-trends.png`. Please mind the potential broken links of images in the respective metric files.

Please take your time and let me know if you have any issues, I can help with them.
@GeorgLink, do you want to add anything more?

**Comment by GeorgLink** [comment]
**.gitignore**

You can just copy-paste the one we have in the D&I WG: https://github.com/chaoss/wg-diversity-inclusion/blob/master/.gitignore

**Comment by GeorgLink** [comment]
Thanks @friyaz for kicking off the work. The feedback @vchrombie provided should help you improve the pull request so we can accept it.

Please let us know if you have any concerns or questions; and thank you for working on this.

**Comment by GeorgLink** [comment]
Hi @friyaz, are you able to continue working on this?

**Comment by faisal-deepsource** [comment]
Hey, I would be glad if someone can take this over.

**Comment by ritik-malik** [comment]
Hey @friyaz @GeorgLink @vchrombie ,
Can I take it from here?
I hope the task won't be much different from what is being done in [wg-risk](https://github.com/chaoss/wg-risk/pull/124)

**Comment by GeorgLink** [comment]
Yes, of course.
Thanks @faisal-deepsource  @friyaz and @ritik-malik

**Comment by GeorgLink** [comment]
replaced by #142

**Pull request closed without merging**
