### PR TITLE
Use Metric Pull Request

### PR DESCRIPTION
**Pull request by bryanprichard13**
Bryan Prichard

This is an metric that overviews the idea of using "Use Statistics" or how many people use the software to measure the software value in a specific area. If the software lacks use then you know it needs either improvement or more advertisement.

### CODE REVIEW

**Comment by mbbroberg** [comment]
Thanks for writing this up @bryanprichard13. I'll dig more into this and bring it up in our next community meeting (next Thursday).

In the meantime, please sign the commits following DCO bot's advice 🤖

**Comment by LawrenceHecht** [comment]
I think the "use metric" is covered in other working groups. At most, "usage" levels are a way to measure a) the value of the experience/skill in an project and 2) the risk of getting involved with the project.

**Comment by mbbroberg** [comment]
Thanks again for this metric proposal. Before we can add it in, we're taking the time to make sure we're answering the right questions with the right metrics. You can see more on how in #88 and join us on June 4th to continue that effort.

**Comment by GeorgLink** [comment]
Thank you again for your PR. I'm closing it for now because it is missing key elements. If you wnat to fix the following points, please open a new issue or PR and let us know.

* Please format the metric using our [Metric Template](https://github.com/chaoss/metrics/blob/master/resources/metrics-template.md)
* Please identify which [focus area](https://github.com/chaoss/wg-value/tree/master/focus-areas) it could belong to
* Please make sure you provide a DCO sign-off on all commits.

**Pull request closed without merging**
