### PR TITLE
README: correct link

### PR DESCRIPTION
**Pull request by mbbroberg**
And refine the contributor pitch.

### CODE REVIEW

**Comment by mbbroberg** [comment]
Shoot. I was able to force push to both the PR branch **and** master. My mistake -- aiming to avoid that next time. 

In the meantime, merging this to get up-to-date with #71, which I thankfully downloaded before erasing it 😅

**Comment by GeorgLink** [comment]
Thanks @mbbroberg !

Should we disable direct push to master and force the PR contribution process?

**Comment by mbbroberg** [comment]
@GeorgLink absolutely! I followed [this guide](https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions) but I'm not sure if it's set up correctly. Please double check when you can.

**Comment by GeorgLink** [comment]
It looks correct :) thank you!

**Pull request merged**
