### PR TITLE
Change pull requests language to change requests 

### PR DESCRIPTION
**Pull request by amruta-kashikar**
Signed-off-by: Amruta Kashikar amrutakashikar2@gmail.com
#119

### CODE REVIEW

**Comment by germonprez** [comment]
Many thanks @amruta-kashikar. Could you provide a brief description of what you did in the comments? I know it's a bit redundant with the title but it helps tracks things. 

Also, you will need to provide a DCO sign-off. Similar to: 

Signed-off-by: Matt Germonprez <germonprez@gmail.com>

But with your info.

**Comment by amruta-kashikar** [comment]
I replaced the metric name pull requests with new metric name change requests as mentioned in the issue

**Comment by germonprez** [comment]
You can just put it in your original comment.

**Comment by klumb** [comment]
This PR will need to be addressed in the next release

**Comment by GeorgLink** [comment]
This PR has a conflict with other changes made to the repository.

**Pull request closed without merging**
